export const MAIN_COLORS = {
  PRIMARY: "#FFFFFF",
  SECONDARY: "#FF6347",
  BACKGROUND: "#121212",
  DANGER: "red",
  INFO: "blue",
  SUCCESS: "green",
  TEXT_PRIMARY: "#FFFFFF",
  TEXT_SECONDARY: "dimmed",
  BLUE_DARK: "var(--mantine-color-blue-dark)",
  GRAY_DARK: "var(--mantine-color-gray-dark)",
  TAB1: "#099CFF",
  TAB2: "#6BD731",
  TAB3: "#C91A25",
  TITLE_COLOR: "blue.7",
  PROEFFICIENT: "yellow",
  NATIVE: "green",
  TEXT_BLUE: "blue",
  PRIMARY_BUTTON: "#228be6",
  SECONDARY_BUTTON: "#00b5e2",
};
